# Generated by Django 5.1.7 on 2026-01-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_new_person_birth_alter_new_person_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Person',
            fields=[
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.new_person')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
