# Generated by Django 5.1.7 on 2026-01-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Person',
            fields=[
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.person')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
