# Generated by Django 5.1.7 on 2026-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_person',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
