# Generated by Django 6.0.1 on 2026-01-28 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.UUIDField(db_column='medication_id', default=uuid.UUID('21041102-274f-43c8-845c-890d857ce5be'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('days', models.CharField(max_length=50)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.new_person')),
            ],
        ),
    ]
