# Generated by Django 6.0.3 on 2026-03-11 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bula_data',
            fields=[
                ('register_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('indicacoes_para_uso', models.TextField()),
                ('funcionamento_medicamento', models.TextField()),
                ('quando_nao_usar', models.TextField()),
                ('conhecimento_previo_necessario', models.TextField()),
                ('como_guardar_medicamento', models.TextField()),
                ('como_usar_medicamento', models.TextField()),
                ('esqueceu_medicamento', models.TextField()),
                ('efeitos_colaterais', models.TextField()),
                ('quantidade_a_mais', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('days', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.new_person')),
            ],
        ),
    ]
