# Generated by Django 5.1.7 on 2026-01-06 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
    ]
