# Generated by Django 5.1.7 on 2026-01-06 18:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medication_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='begin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='end',
            field=models.DateField(default=datetime.datetime(2026, 1, 1, 8, 0)),
            preserve_default=False,
        ),
    ]
