# Generated by Django 5.1.7 on 2026-01-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_medication_begin_medication_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='time_of_day',
        ),
    ]
