# Generated by Django 5.1.7 on 2026-01-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_remove_medication_time_of_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
