# Generated by Django 5.1.7 on 2026-01-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_medicationtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationTime',
        ),
    ]
