# Generated by Django 5.1.7 on 2026-01-12 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0006_delete_medicationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='day',
            field=models.CharField(default=datetime.date(2026, 1, 12), max_length=50),
            preserve_default=False,
        ),
    ]
