# Generated by Django 5.1.7 on 2026-01-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0007_medication_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='day',
            new_name='days',
        ),
    ]
