# Generated by Django 5.1.7 on 2026-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
