# Generated by Django 5.1.7 on 2026-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_person',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_person',
            name='email',
            field=models.CharField(default='seu_email_aqui@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='new_person',
            name='password',
            field=models.CharField(default='sua_senha_aqui', max_length=255),
        ),
    ]
