# Generated by Django 5.1.7 on 2026-01-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField()),
            ],
        ),
    ]
